### ISSUE TITLE
Update the documentation

### ISSUE THREAD

**Issue by EnriqueVidal** [rubytij/usergroup#11]
Someone please fill the wiki with info about how to run de app in development and any caveats that may exist.

We also need contributors instructions and ground rules published there.

**Comment by sibarra** [comment]
Alright, I'm currently writing one on how to clone the project and run the basic things, if you could check it out later for errors or whatever

**Comment by EnriqueVidal** [comment]
Sure thing let me know when and what to look at.

**Comment by sibarra** [comment]
Its already in the wiki:  https://github.com/rubytij/usergroup/wiki/Setting-up-your-local-development-environment

**Comment by EnriqueVidal** [comment]
I updated the wiki again, there are still some stuff we need to cover in it.

**Comment by EnriqueVidal** [comment]
This has been taken care of.
