### ISSUE TITLE
User authorization

### ISSUE THREAD

**Issue by EnriqueVidal** [rubytij/usergroup#2]
Anyone can create their own posts but only certain people can edit the main page.

**Comment by javierg** [comment]
We will need to define the Roles based on GH street cred, so what will be those Roles:
- Owner: not based on streetcred but census
- Moderator: full CRUD to posts
- Editor: can create posts, also can annotate others people posts
- Colaboratos: can create posts.

This is open to discussion

**Comment by EnriqueVidal** [comment]
Your description of the roles looks about right, we could get all of them from GH by creating each of those groups within our org and selectively (based on participation) move people in each of them.

You shouldn't need a role to create posts though just join the app.
