### ISSUE TITLE
Rake on Ruby 1.8.7 returns Library not loaded: /opt/local/lib/libffi.5.dylib ERROR

### ISSUE THREAD

**Issue by javierg** [rubytij/usergroup#53]
I guess this is an error with my local config, but I can;t make it work... all google search says is a ruby 1.9 issue

**Comment by EnriqueVidal** [comment]
This must be your local installation because we're building in 1.8.7 with no problem.

**Comment by alexperto** [comment]
I'm using rvm, and I resolved it by reinstalling the ffi gem

```
gem uninstall ffi
gem install ffi
```

Now I can use ruby 1.9.3
I hope it helps! @javierg
